### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/react-google-maps#592]
### Description

I was trying to add a google firebase login to multimap example (https://visgl.github.io/react-google-maps/examples/multiple-maps, example is certainly working). 
![empty](https://github.com/user-attachments/assets/7a40b114-fb92-4996-9717-1afca5b90c74)
![login-screen](https://github.com/user-attachments/assets/2f559b1a-5f66-44ae-9293-47a91b84d8f2)
![normal](https://github.com/user-attachments/assets/3899c2e1-615c-4f3a-bf2c-9fb3ddab07fe)

First, i created a empty login with only firebase code, 
login name: qiaoxin136@gmail.com
password: 123456
it worked and showed a welcome message, (see login-screen.png)
then i added the multiplemap code, the multiple maps does not show up at all. Nothing. (see empty.png)
I am not sure if there is a bug here or it is google firebase problem. 

### Steps to Reproduce

the working empty login can be seen in 
https://codesandbox.io/p/github/qiaoxin136/login-empty/draft/autumn-pine?workspaceId=d68df01c-f46f-497c-bfee-4134267b36a9

the login with map (showing empty result) can be seen in 

https://codesandbox.io/p/github/qiaoxin136/login-map/main?workspaceId=d68df01c-f46f-497c-bfee-4134267b36a9

again login name: qiaoxin136@gmail.com password: 123456

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

### Logs

```text
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hi')
    at google.maps.__gjsload__._.ar (common.js:7:229)
    at Hn.<anonymous> (map.js:58:206)
    at _.Dk (js?key=AIzaSyBsntctk…hzbQZ_d4gsw:173:457)
    at map.js:58:142
    at new Promise (<anonymous>)
    at Nwa.swa [as sF] (map.js:58:114)
    at js?key=AIzaSyBsntctk…NhzbQZ_d4gsw:240:78
```

**Comment by usefulthink** [comment]
The second link you shared is returning an error "Insufficient access". Can you check if the workspace is publicly available?

**Comment by qiaoxin136** [comment]
codesandbox does not allow public. below is a shared link. if it does not work, can you give me an email address to share with you? or you can direct me to use other similar service. 


https://codesandbox.io/p/github/qiaoxin136/login-map/draft/nifty-dust
